---
- hosts: all
  tasks:
    - include: "{{ item }}"
      with_first_found:
        - 'environments/{{ env }}/hosts_vars/{{ ansible_fqdn }}.yaml'
        - 'environments/{{ env }}/hosts_vars/main.yaml'
    - include: "{{ item }}"
      with_first_found:
        - 'environments/{{ env }}/hosts_secret_vars/{{ ansible_fqdn }}.yaml'
        - 'environments/{{ env }}/hosts_secret_vars/main.yaml'
  vars_files:
    - 'environments/{{ env }}/group_vars/main.yaml'
  roles:
    - common
    - ntp
