---
- hosts: all
  tasks:
  - include_vars:
      dir: 'environments/{{ env }}/group_vars/'
      files_matching: '.*.yaml'
  - include_vars:
      dir: 'environments/{{ env }}/hosts_vars/'
      files_matching: '{{ ansible_fqdn }}.yaml'
  - include_vars:
      dir: 'environments/{{ env }}/hosts_vars_secret/'
      files_matching: '{{ ansible_fqdn }}.secret.yaml'
    ignore_errors: true
  roles:
    - common
    - ntp

- hosts: etcd
  vars_files:
    - 'environments/{{ env }}/group_vars/main.yaml'
  roles:
    - etcd
