---
- name: create Kubernetes configuration in place
  template:
    src: master_config.j2
    dest: '/etc/kubernetes/config'
    mode: 0644

- name: create Kubernetes APIserver configuration in place
  template:
    src: master_apiserver.j2
    dest: '/etc/kubernetes/apiserver'
    mode: 0644

- name: create Kubernetes configuration in place
  template:
    src: master_controller-manager.j2
    dest: '/etc/kubernetes/controller-manager'
    mode: 0644

- name: create Kubernetes configuration in place
  template:
    src: master_scheduler.j2
    dest: '/etc/kubernetes/scheduler'
    mode: 0644

- name: restart kube-apiserver
  service:
    name: kube-apiserver
    state: restarted
    enabled: yes

- name: restart kube-controller-manager
  service:
    name: kube-controller-manager
    state: restarted
    enabled: yes

- name: restart kube-scheduler
  service:
    name: kube-scheduler
    state: restarted
    enabled: yes
