---
- name: create SSL certs directory
  file:
    path: '{{ k8s_certs_directory }}'
    state: directory
    mode: 0755

- name: create tokens directory
  file:
    path: '{{ k8s_tokens_directory }}'
    state: directory
    mode: 0755

- name: copy SSL certs from {{ groups['k8s'][0] }}
  synchronize:
    src: '{{ k8s_certs_directory }}'
    dest: '/etc/kubernetes'
  delegate_to: "{{ groups['k8s'][0] }}"

- name: copy token file from {{ groups['k8s'][0] }}
  synchronize:
    src: '{{ k8s_tokens_directory }}'
    dest: '/etc/kubernetes'
  delegate_to: "{{ groups['k8s'][0] }}"
