---
# Kubernetes roles: master or node
kubernetes_role: 'node'
k8s_ssl_support: true
k8s_generate_ssl_certs: true
k8s_certs_directory: '/etc/kubernetes/certs'
k8s_loadbalancer_domain: 'lb.vagrant.loc'
k8s_loadbalancer_ip: '192.168.10.100'
k8s_service_ip: '10.1.0.1'
k8s_nodes:
  - node1.vagrant.loc
  - node2.vagrant.loc

###
# Kubernetes master
###
# RPMs list
k8s_master_rpms_list:
  - kubernetes-master
  - openssl

###
# Kubernetes node
###
# RPMs list
k8s_node_rpms_list:
  - kubernetes-node
