---
- name: install base packages
  yum:
    name: '{{ item }}'
    state: present
  with_items: '{{ packages_list }}'

- name: install extra packages
  yum:
    name: '{{ item }}'
    state: present
  with_items: '{{ extra_packages_list }}'
  when: extra_packages_list is defined
