---
- name: install base packages
  yum:
    name: '{{ item }}'
    state: present
  with_items: '{{ packages_list }}'
  when: packages_list is defined

- name: install extra packages
  yum:
    name: '{{ item }}'
    state: present
  with_items: '{{ extra_packages_list }}'
  when: extra_packages_list is defined

- name: turn on system log commpression
  replace:
    dest: '/etc/logrotate.conf'
    regexp: '^#compress'
    replace: 'compress'
