---
- name: kubectl config set-cluster
  shell: 'kubectl config set-cluster kubecluster --server=https://{{ k8s_loadbalancer_domain }}:6443 --insecure-skip-tls-verify=true'

- name: kubectl config unset clusters
  shell: 'kubectl config unset clusters'

- name: kubectl config set-cluster with certs
  shell: 'kubectl config set-cluster kubecluster --certificate-authority={{ k8s_certs_directory }}/ca.crt --embed-certs=true --server=https://{{ k8s_loadbalancer_domain }}:6443'

- name: get k8s auth token from file and register as variable
  shell: "cat {{ k8s_tokens_directory }}/known_tokens.csv | awk -F, '{print $1}'"
  register: k8s_auth_token

### Naprawic TOKEN
- name: kubectl config set-credentials kubelet
  shell: 'kubectl config set-credentials kubelet --client-certificate={{ k8s_certs_directory }}/{{ ansible_fqdn }}.crt --client-key={{ k8s_certs_directory }}/{{ ansible_fqdn }}.key --embed-certs=true --token={{ k8s_auth_token.stdout }}'

- name: kubectl config set-context service-account-context
  shell: 'kubectl config set-context service-account-context --cluster=kubecluster --user=kubelet'

- name: kubectl config use-context service-account-context
  shell: 'kubectl config use-context service-account-context'
